# Generated by Django 5.2.7 on 2025-11-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarian',
            old_name='books',
            new_name='library',
        ),
    ]
